version: '3'
services:
  bot:
    build: .
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
  redis:
    image: redis:latest
  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

